checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.18
      ini:
        apc.enable_cli: 1
        apc.enable: 1
        memory_limit: -1
        xdebug.mode: coverage

  nodes:
    analysis:
      dependencies:
        override:
          - pecl install apcu

      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      dependencies:
        override:
          - pecl install apcu
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
